# Generated by Django 3.2.12 on 2022-04-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220410_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stripeCustomerId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
