# Generated by Django 3.2.12 on 2022-03-21 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address1',
            field=models.CharField(default='7 Sundorne', max_length=80),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='UK', max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(default='LL13 0EB', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.IntegerField(choices=[(None, 'Choose a subscription'), (0, 'Complimentary'), (1, 'Trainee (6 month)'), (2, 'Driving Instuctor (monthly)'), (3, 'Driving Instuctor (annual)')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='town',
            field=models.CharField(default='Wrecsam', max_length=40),
        ),
    ]
