# Generated by Django 3.2.12 on 2022-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220321_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.IntegerField(choices=[(None, 'Choose a subscription'), (0, 'Complimentary'), (1, 'Trainee (6 month)'), (2, 'Driving Instuctor (monthly)'), (3, 'Driving Instuctor (annual)')], default=0),
        ),
    ]
