# Generated by Django 3.2.12 on 2022-03-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='county',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_duration',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_end_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_start_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='town',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'PDI'), (1, 'ADI'), (2, 'Pupil')], default=2, editable=False),
            preserve_default=False,
        ),
    ]
