# Generated by Django 3.2.12 on 2022-04-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.IntegerField(blank=True, choices=[(0, 'PDI'), (1, 'ADI'), (2, 'Pupil')], null=True),
        ),
    ]
