# Generated by Django 3.2.12 on 2022-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220401_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_uuid',
            field=models.CharField(default=0, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
