# Generated by Django 3.2.12 on 2022-03-22 21:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_contact_id', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('customer_type', models.IntegerField(choices=[(1, 'Learner'), (2, 'Trainee (PDI)')])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balance_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('balance_payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=80)),
                ('address2', models.CharField(blank=True, max_length=80, null=True)),
                ('town', models.CharField(max_length=40)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=40)),
                ('active', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lesson', models.DateField(default=datetime.date.today)),
                ('time_of_lesson', models.TimeField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=2)),
                ('payment_taken', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressrecord', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Subject')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.subjectcategories', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comments', models.TextField()),
                ('practice_next_lesson', models.BooleanField()),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressitems', to='customers.progress')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='customers.subjects')),
            ],
        ),
    ]
