# Generated by Django 3.2.12 on 2022-03-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgressItems',
            new_name='ProgressItem',
        ),
    ]
